---
title: MJP
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
permalink: pretty
plugins:
- jekyll-paginate
paginate: 5
paginate_path: blog/page:num
tagline: designer • coder • strategist • educator
description: Homepage and blog of Miles Jonathan Phillips, UK based architect
url: https://milesjphillips.com
author:
  name: Miles J Phillips
  url: https://twitter.com/millipz
  email: milesjphillips@gmail.com
version: 0.1.0
