# Permalinks
#
permalink:           pretty

# Fix for permalinks
#
gems: [jekyll-paginate]
paginate: 5
paginate_path: "blog/page:num"

# Setup
title:               The Rivers
tagline:             'Groove Driven Acapella'
description:         'Oxford Based Acapella Group'
url:                 http://theriversacapella.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Miles J Phillips
  url:               https://twitter.com/millipz
  email:             milesjphillips@gmail.com

# Custom vars
version:             0.1.0
